### ISSUE TITLE
How to use shpc add command to create a new registry entry?

### ISSUE THREAD

**Issue by gq1** [singularityhub/singularity-hpc#542]
Tried different ways to use `shpc add ` command, it seems the `container.yaml` generated not really helpful.

```
shpc add docker://quay.io/repository/biocontainers/pretextmap
shpc add docker://quay.io/repository/biocontainers/pretextmap quay.io/biocontainers/pretextmap/0.1.9--h9f5acd7_1
```

only module name and url being populated but not really what I wanted:
url not what I passed in and I don't want repository in module name like all others from quay.io/biocontainers

```
# change this to a URL to describe your container, or to get help
url: https://singularity-hpc.readthedocs.io

# change this to your GitHub alias (or another contact or name)
maintainer: Dinosaur

# Any custom features?
# features:
#  gpu: true

# Put custom aliases here
# aliases:
#  echo: /usr/bin/echo

# custom environment variables
# env:
#  breakfast: pancakes

# A description to describe your container
description: A custom container to do X.
latest:
  latest: 'crane digest quay.io/repository/biocontainers/pretextmap:latest: NAME_INVALID:
    Nested repositories are not supported. Found: repository/biocontainers/pretextmap;
    map[]'
tags:
  latest: 'crane digest quay.io/repository/biocontainers/pretextmap:latest: NAME_INVALID:
    Nested repositories are not supported. Found: repository/biocontainers/pretextmap;
    map[]'
docker: quay.io/repository/biocontainers/pretextmap
```

**Comment by vsoch** [comment]
You pasted the url from quay  - you should remove the “repository” bit because that’s not part of an actual container URI.

**Comment by vsoch** [comment]
shpc add docker://quay.io/biocontainers/pretextmap

**Comment by gq1** [comment]
Thanks, that looks much better.

**Comment by muffato** [comment]
This is the file it creates
```
# change this to a URL to describe your container, or to get help
url: https://singularity-hpc.readthedocs.io

# change this to your GitHub alias (or another contact or name)
maintainer: Dinosaur

# Any custom features?
# features:
#  gpu: true

# Put custom aliases here
# aliases:
#  echo: /usr/bin/echo

# custom environment variables
# env:
#  breakfast: pancakes

# A description to describe your container
description: A custom container to do X.
latest:
  latest: 'crane digest quay.io/biocontainers/pretextmap:latest: MANIFEST_UNKNOWN:
    manifest unknown; map[]'
tags:
  latest: 'crane digest quay.io/biocontainers/pretextmap:latest: MANIFEST_UNKNOWN:
    manifest unknown; map[]'
docker: quay.io/biocontainers/pretextmap
```
You can see it's missing the checksums

**Comment by muffato** [comment]
Sorry, what does that mean :grimacing: ?

**Comment by muffato** [comment]
Ah, I didn't specify the tag in the `shpc add` command and there is no `latest` ! 🤦🏼

**Comment by vsoch** [comment]
@muffato we probably should have a nicer error message than having it appear to work! I'll put in a PR for this in the evening.

**Comment by vsoch** [comment]
okay see https://github.com/singularityhub/singularity-hpc/pull/543 ! This will give a more explicit error message that we could not find the tag, and prompt the person to check the tag and container URI. it's pretty bad now that it fails silently and then gives you that wackadoo yaml.

**Comment by gq1** [comment]
Thanks.

Tested your new branch.

`shpc add docker://quay.io/biocontainers/pretextmap`
Exited without yaml file generated.

`shpc add docker://quay.io/biocontainers/pretextmap:0.1.9--h9f5acd7_1`
This works fine.
```
# change this to a URL to describe your container, or to get help
url: https://singularity-hpc.readthedocs.io

# change this to your GitHub alias (or another contact or name)
maintainer: Dinosaur

# Any custom features?
# features:
#  gpu: true

# Put custom aliases here
# aliases:
#  echo: /usr/bin/echo

# custom environment variables
# env:
#  breakfast: pancakes

# A description to describe your container
description: A custom container to do X.
latest:
  0.1.9--h9f5acd7_1: sha256:2ea29e078166daa95ea28d500cd2df46eec77cebc9d100ed986f797e3a282ae1
tags:
  0.1.9--h9f5acd7_1: sha256:2ea29e078166daa95ea28d500cd2df46eec77cebc9d100ed986f797e3a282ae1
docker: quay.io/biocontainers/pretextmap
```
