### ISSUE TITLE
Interaction between separate modules

### ISSUE THREAD

**Issue by JossWhittle** [singularityhub/singularity-hpc#544]
Consider the `container.yaml` snippets that define two modules. Relion has both command line utilities and a GUI (which has been aliased), Motioncor2 aliases a command line program.

```yaml
docker: quay.io/rosalindfranklininstitute/relion
features:
  gpu: true
  x11: true
aliases:
  relion: /usr/local/relion/bin/relion
  ...
  relion_refine_mpi: /usr/local/relion/bin/relion_refine_mpi
```

```yaml
docker: quay.io/rosalindfranklininstitute/motioncor2
features:
  gpu: true
aliases:
  motioncor2: /usr/local/motioncor2/bin/motioncor2
```

Relion is usually used by domain scientists through the GUI. Internally the GUI will execute one or more of Relions command line utilities, each of which may then access the GPU. 

Motioncor2 can be run standalone on the CLI, but more generally will be called from the Relion GUI using a path to the executable. However, the latter (running motioncor2 via the GUI) is equivalent to running it through the `relion-run` wrapper which I will use in examples here for clarity:

```bash
module load motioncor2 relion

relion                # works and shows GUI!
relion_refine_mpi     # works on CLI!
motioncor2            # works on CLI!

relion-run motioncor2 
# does not work, can't find motioncor2 on PATH within relion container

# enabling wrapper scripts in settings.yaml rather than the default of using 
# shell functions gets us a step closer since we can see the path from the host
relion-run /path/to/modules/motioncor2/bin/motioncor2 
# but still does not work, the wrapper script is found on the host system correctly, 
# but the relion container does not have singularity installed so it cannot 
# execute the motioncor2 container
```

Is there a good solution to this problem already in place, where module containers need to call each others exposed aliases? Is installing singularity in all the module containers to allow them to nest with each other a valid solution?

Vis-à-vis nesting singularity container instances I found this related issue: https://github.com/apptainer/singularity/issues/5759#issuecomment-919523970
Is this workaround still required? It could potentially be injected into wrapper scripts using a snippet.
