### ISSUE TITLE
Generating shell scripts instead of functions for wrappers without specifying on the container.yaml

### ISSUE THREAD

**Issue by surak** [singularityhub/singularity-hpc#565]
As the wrapper_scripts option is now enabled by default, shpc will only create scripts in cases the container.yaml file has the docker_scripts/singularity_scripts tag.

My suggestion would be that, instead of creating functions for calling the containers, simple default shell scripts with such content be created instead. This way, `slurm` and others will be happy to call it. 

The current default is to only generate shell scripts if there's enough info on the container.yaml.

Changes needed:
- The module would need to export a path, which is not done now.
- Each function (like container_run, container_exec, container_container, container_shell) gets created as a shell script instead of a function.

What do you think? That's better than to have to add a script/wrapper entry to every single container in the registry.

**Comment by vsoch** [comment]
Hmm this sounds like a bug - the scripts should generate using the default templates from the settings.yaml. @muffato was this added with the PR that updated wrapper scripts?

**Comment by muffato** [comment]
Yes, it sounds like a bug too ! Scripts should be created regardless of whether they have a template defined / overwritten in `singularity_scripts`. I can take a look later tonight

**Comment by vsoch** [comment]
@surak that would be great if you could give the complete steps you took so we can reproduce! I can try as well.

**Comment by surak** [comment]
```bash
 find .
.
./nvcr.io
./nvcr.io/nvidia
./nvcr.io/nvidia/tensorflow
./nvcr.io/nvidia/tensorflow/.version
./nvcr.io/nvidia/tensorflow/22.06-tf2-py3
./nvcr.io/nvidia/tensorflow/22.06-tf2-py3/module.lua
./nvcr.io/nvidia/tensorflow/22.06-tf2-py3/99-shpc.sh
./nvcr.io/nvidia/tensorflow/22.06-tf2-py3/nvcr.io-nvidia-tensorflow-22.06-tf2-py3-sha256:ea76aabaa17ee0e308a443fa1e7666f98350865f266b02610a60791bd0feeb40.sif
```

I can confirm that quay.io works with the aliases containing in the container.yaml file, but not the template functions.

**Comment by surak** [comment]
So, I think it's a different thing.

In quay.io/biocontainers/blast/container.yaml, the aliases are like this:

```
aliases:
  blast_formatter: /usr/local/bin/blast_formatter
  blastdb_aliastool: /usr/local/bin/blastdb_aliastool
  blastdbcheck: /usr/local/bin/blastdbcheck
  blastdbcmd: /usr/local/bin/blastdbcmd
  blastn: /usr/local/bin/blastn
  blastp: /usr/local/bin/blastp
  blastx: /usr/local/bin/blastx
  cleanup-blastdb-volumes.py: /usr/local/bin/cleanup-blastdb-volumes.py
  convert2blastmask: /usr/local/bin/convert2blastmask
  deltablast: /usr/local/bin/deltablast
  eblast: /usr/local/bin/eblast
  makeblastdb: /usr/local/bin/makeblastdb
  psiblast: /usr/local/bin/psiblast
  rpsblast: /usr/local/bin/rpsblast
  rpstblastn: /usr/local/bin/rpstblastn
  tblastn: /usr/local/bin/tblastn
  tblastx: /usr/local/bin/tblastx
  update_blastdb.pl: /usr/local/bin/update_blastdb.pl
```

Which make sense: they are aliases to binaries on the filesystem of the container.

This is related to the aliases generated in the template. For example, here: https://github.com/singularityhub/singularity-hpc/blob/main/shpc/main/modules/templates/singularity.lua , where you have

```lua
 - {|module_name|}-run:
       singularity run {% if features.gpu %}{{ features.gpu }} {% endif %}{% if features.home %}-B {{ features.home }} --home {{ features.home }} {% endif %}{% if features.x11 %}-B {{ features.x11 }} {% endif %}{% if settings.environment_file %}-B <moduleDir>/{{ settings.environment_file }}:/.singularity.d/env/{{ settings.environment_file }}{% endif %} {% if settings.bindpaths %}-B {{ settings.bindpaths }} {% endif %}<container> "$@"
 - {|module_name|}-shell:
       singularity shell -s {{ settings.singularity_shell }} {% if features.gpu %}{{ features.gpu }} {% endif %}{% if features.home %}-B {{ features.home }} --home {{ features.home }} {% endif %}{% if features.x11 %}-B {{ features.x11 }} {% endif %}{% if settings.environment_file %}-B <moduleDir>/{{ settings.environment_file }}:/.singularity.d/env/{{ settings.environment_file }}{% endif %} {% if settings.bindpaths %}-B {{ settings.bindpaths }} {% endif %}<container>
 - {|module_name|}-exec:
       singularity exec {% if features.gpu %}{{ features.gpu }} {% endif %}{% if features.home %}-B {{ features.home }} --home {{ features.home }} {% endif %}{% if features.x11 %}-B {{ features.x11 }} {% endif %}{% if settings.environment_file %}-B <moduleDir>/{{ settings.environment_file }}:/.singularity.d/env/{{ settings.environment_file }}{% endif %} {% if settings.bindpaths %}-B {{ settings.bindpaths }} {% endif %}<container> "$@"
 - {|module_name|}-inspect-runscript:
       singularity inspect -r <container>
 - {|module_name|}-inspect-deffile:
       singularity inspect -d <container>
 - {|module_name|}-container:
       echo "$SINGULARITY_CONTAINER"
```

Those won't work in Slurm.
